#minimumReleaseAge: 100080
minimumReleaseAgeExclude:
  - mlform@0.1.23
  - "@tanstack/query-core@5.101.3"
  - "@tanstack/react-query@5.101.3"
  - monaco-editor@0.56.0
  - read-excel-file@9.3.3
  - recharts@3.10.0

#  - react-doctor@0.8.1
#trustPolicy: no-downgrade
#trustPolicyExclude:
#  - semver@6.3.1
