ALTER TABLE model
    ADD COLUMN artifact_sha256 VARCHAR(64),
    ADD COLUMN storage_version_id VARCHAR(255),
    ADD COLUMN artifact_state VARCHAR(32),
    ADD COLUMN artifact_verified_at TIMESTAMPTZ,
    ADD COLUMN artifact_migration_attempts INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN artifact_migration_error VARCHAR(1000),
    ADD COLUMN artifact_migration_started_at TIMESTAMPTZ,
    ADD COLUMN artifact_migration_worker VARCHAR(128);

UPDATE model
SET artifact_state = CASE
    WHEN storage_object_key IS NOT NULL THEN 'UNVERIFIED'
    ELSE 'INLINE_ONLY'
END;

ALTER TABLE model
    ALTER COLUMN artifact_state SET NOT NULL,
    ADD CONSTRAINT ck_model_artifact_state CHECK (
        artifact_state IN ('INLINE_ONLY', 'UNVERIFIED', 'RUNNING', 'VERIFIED', 'FAILED')
    ),
    ADD CONSTRAINT ck_model_artifact_sha256 CHECK (
        artifact_sha256 IS NULL OR artifact_sha256 ~ '^[0-9a-f]{64}$'
    );

CREATE INDEX idx_model_artifact_migration
    ON model (artifact_state, artifact_migration_started_at, id);

ALTER TABLE plugin_metadata
    ADD COLUMN sha256 VARCHAR(64),
    ADD COLUMN storage_version_id VARCHAR(255),
    ADD CONSTRAINT ck_plugin_metadata_sha256 CHECK (
        sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$'
    );

CREATE TABLE storage_deletion_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket VARCHAR(100) NOT NULL,
    object_key VARCHAR(512) NOT NULL,
    object_version_id VARCHAR(255),
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_storage_deletion_object UNIQUE (bucket, object_key),
    CONSTRAINT ck_storage_deletion_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX idx_storage_deletion_pending
    ON storage_deletion_task (status, next_attempt_at, id);
