-- A prediction run a member explicitly marked as a public example of a bookmark. The run stays
-- the source of truth for the inputs: nothing is copied here. An example is served only while
-- the bookmark is public and still pins the snapshot the run executed on, so a moved bookmark
-- needs no cleanup. Rows leave with their run or their bookmark.
CREATE TABLE schema_bookmark_example (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    schema_bookmark_id BIGINT NOT NULL,
    prediction_run_id BIGINT NOT NULL,
    public_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_schema_bookmark_example_bookmark_run UNIQUE (schema_bookmark_id, prediction_run_id),
    CONSTRAINT uq_schema_bookmark_example_public_id UNIQUE (public_id),
    CONSTRAINT fk_schema_bookmark_example_bookmark FOREIGN KEY (schema_bookmark_id)
        REFERENCES schema_bookmark ON DELETE CASCADE,
    CONSTRAINT fk_schema_bookmark_example_run FOREIGN KEY (prediction_run_id)
        REFERENCES prediction_run ON DELETE CASCADE
);

CREATE INDEX idx_schema_bookmark_example_run ON schema_bookmark_example (prediction_run_id);
