import type { Model, Prediction, Signature } from "./hooks"

export const mockModels: Model[] = [
    {
        id: "model-1",
        name: "Customer Churn Predictor",
        type: "classification",
        accuracy: 0.892,
        lastTrained: "2024-01-15",
        status: "active",
        fileName: "churn_predictor_v2.joblib",
        createdAt: "2024-01-10",
    },
    {
        id: "model-2",
        name: "Customer Churn Predictor",
        type: "classification",
        accuracy: 0.892,
        lastTrained: "2024-01-15",
        status: "active",
        fileName: "churn_predictor_v2.joblib",
        createdAt: "2024-01-10",
    },
    {
        id: "model-3",
        name: "Customer Churn Predictor",
        type: "classification",
        accuracy: 0.892,
        lastTrained: "2024-01-15",
        status: "active",
        fileName: "churn_predictor_v2.joblib",
        createdAt: "2024-01-10",
    },
    {
        id: "model-4",
        name: "Customer Churn Predictor",
        type: "classification",
        accuracy: 0.892,
        lastTrained: "2024-01-15",
        status: "active",
        fileName: "churn_predictor_v2.joblib",
        createdAt: "2024-01-10",
    },
    {
        id: "model-5",
        name: "Customer Churn Predictor",
        type: "classification",
        accuracy: 0.892,
        lastTrained: "2024-01-15",
        status: "active",
        fileName: "churn_predictor_v2.joblib",
        createdAt: "2024-01-10",
    },
    {
        id: "model-6",
        name: "Customer Churn Predictor",
        type: "classification",
        accuracy: 0.892,
        lastTrained: "2024-01-15",
        status: "active",
        fileName: "churn_predictor_v2.joblib",
        createdAt: "2024-01-10",
    },
    {
        id: "model-7",
        name: "Customer Churn Predictor",
        type: "classification",
        accuracy: 0.892,
        lastTrained: "2024-01-15",
        status: "active",
        fileName: "churn_predictor_v2.joblib",
        createdAt: "2024-01-10",
    },
    {
        id: "model-8",
        name: "Customer Churn Predictor",
        type: "classification",
        accuracy: 0.892,
        lastTrained: "2024-01-15",
        status: "active",
        fileName: "churn_predictor_v2.joblib",
        createdAt: "2024-01-10",
    },
    {
        id: "model-9",
        name: "Customer Churn Predictor",
        type: "classification",
        accuracy: 0.892,
        lastTrained: "2024-01-15",
        status: "active",
        fileName: "churn_predictor_v2.joblib",
        createdAt: "2024-01-10",
    },
    {
        id: "model-10",
        name: "Customer Churn Predictor",
        type: "classification",
        accuracy: 0.892,
        lastTrained: "2024-01-15",
        status: "active",
        fileName: "churn_predictor_v2.joblib",
        createdAt: "2024-01-10",
    },
    {
        id: "model-11",
        name: "Customer Churn Predictor",
        type: "classification",
        accuracy: 0.892,
        lastTrained: "2024-01-15",
        status: "active",
        fileName: "churn_predictor_v2.joblib",
        createdAt: "2024-01-10",
    },
    {
        id: "model-12",
        name: "Sales Forecasting Model",
        type: "regression",
        accuracy: 0.847,
        lastTrained: "2024-01-12",
        status: "active",
        fileName: "sales_forecast.pkl",
        createdAt: "2024-01-08",
    },
    {
        id: "model-13",
        name: "Fraud Detection System",
        type: "classification",
        accuracy: 0.956,
        lastTrained: "2024-01-08",
        status: "training",
        fileName: "fraud_detector_v3.joblib",
        createdAt: "2024-01-05",
    },
]

export const mockSignatures: Signature[] = [
    // Model 1 Signatures
    {
        id: "sig-1-1",
        modelId: "model-1",
        name: "Churn Prediction v2.1",
        version: "2.1.0",
        createdAt: "2024-01-15",
        inputFeatures: ["age", "tenure", "monthly_charges", "total_charges"],
        outputType: "binary",
        performance: 0.892,
        status: "active",
        schema: {
            inputs: {
                age: { type: "number", required: true, description: "Customer age", min: 18, max: 100 },
                tenure: { type: "number", required: true, description: "Months as customer", min: 0, max: 120 },
                monthly_charges: { type: "number", required: true, description: "Monthly charges in USD", min: 0 },
                total_charges: { type: "number", required: true, description: "Total charges in USD", min: 0 },
            },
            output: {
                type: "string",
                description: "Churn prediction",
                classes: ["Churn", "No Churn"],
            },
            metadata: {
                model_type: "classification",
                version: "2.1.0",
                created_by: "Data Science Team",
                description: "Predicts customer churn based on usage patterns",
            },
        },
    },
    {
        id: "sig-1-2",
        modelId: "model-1",
        name: "Churn Prediction v2.0",
        version: "2.0.0",
        createdAt: "2024-01-10",
        inputFeatures: ["age", "tenure", "monthly_charges"],
        outputType: "binary",
        performance: 0.876,
        status: "deprecated",
        schema: {
            inputs: {
                age: { type: "number", required: true, description: "Customer age", min: 18, max: 100 },
                tenure: { type: "number", required: true, description: "Months as customer", min: 0, max: 120 },
                monthly_charges: { type: "number", required: true, description: "Monthly charges in USD", min: 0 },
            },
            output: {
                type: "string",
                description: "Churn prediction",
                classes: ["Churn", "No Churn"],
            },
            metadata: {
                model_type: "classification",
                version: "2.0.0",
                created_by: "Data Science Team",
                description: "Previous version of churn predictor",
            },
        },
    },
    // Model 2 Signatures
    {
        id: "sig-2-1",
        modelId: "model-2",
        name: "Sales Forecast Q1",
        version: "1.0.0",
        createdAt: "2024-01-12",
        inputFeatures: ["historical_sales", "seasonality", "marketing_spend"],
        outputType: "regression",
        performance: 0.847,
        status: "active",
        schema: {
            inputs: {
                historical_sales: { type: "number", required: true, description: "Previous period sales", min: 0 },
                seasonality: { type: "number", required: true, description: "Seasonal factor", min: 0, max: 2 },
                marketing_spend: { type: "number", required: true, description: "Marketing budget", min: 0 },
            },
            output: {
                type: "number",
                description: "Predicted sales amount",
            },
            metadata: {
                model_type: "regression",
                version: "1.0.0",
                created_by: "Sales Analytics Team",
                description: "Forecasts quarterly sales based on historical data",
            },
        },
    },
    {
        id: "sig-2-2",
        modelId: "model-2",
        name: "Sales Forecast Enhanced",
        version: "1.1.0",
        createdAt: "2024-01-16",
        inputFeatures: ["historical_sales", "seasonality", "marketing_spend", "competitor_data"],
        outputType: "regression",
        performance: 0.863,
        status: "testing",
        baseSignatureId: "sig-2-1",
        schema: {
            inputs: {
                historical_sales: { type: "number", required: true, description: "Previous period sales", min: 0 },
                seasonality: { type: "number", required: true, description: "Seasonal factor", min: 0, max: 2 },
                marketing_spend: { type: "number", required: true, description: "Marketing budget", min: 0 },
                competitor_data: { type: "number", required: true, description: "Competitor market share", min: 0, max: 1 },
            },
            output: {
                type: "number",
                description: "Enhanced sales prediction",
            },
            metadata: {
                model_type: "regression",
                version: "1.1.0",
                created_by: "Sales Analytics Team",
                description: "Enhanced sales forecast with competitor analysis",
            },
        },
    },
    // Model 3 Signatures
    {
        id: "sig-3-1",
        modelId: "model-3",
        name: "Fraud Detection Real-time",
        version: "3.0.0",
        createdAt: "2024-01-08",
        inputFeatures: ["transaction_amount", "location", "time", "merchant_type"],
        outputType: "binary",
        performance: 0.956,
        status: "active",
        schema: {
            inputs: {
                transaction_amount: { type: "number", required: true, description: "Transaction amount", min: 0 },
                location: { type: "string", required: true, description: "Transaction location" },
                time: { type: "string", required: true, description: "Transaction time (HH:MM)" },
                merchant_type: {
                    type: "string",
                    required: true,
                    description: "Type of merchant",
                    enum: ["Grocery", "Electronics", "Gas", "Restaurant", "Online"],
                },
            },
            output: {
                type: "string",
                description: "Fraud detection result",
                classes: ["Fraud", "Legitimate"],
            },
            metadata: {
                model_type: "classification",
                version: "3.0.0",
                created_by: "Security Team",
                description: "Real-time fraud detection system",
            },
        },
    },
    {
        id: "sig-3-2",
        modelId: "model-3",
        name: "Fraud Detection Batch",
        version: "2.5.0",
        createdAt: "2024-01-05",
        inputFeatures: ["transaction_amount", "location", "merchant_type"],
        outputType: "binary",
        performance: 0.943,
        status: "deprecated",
        schema: {
            inputs: {
                transaction_amount: { type: "number", required: true, description: "Transaction amount", min: 0 },
                location: { type: "string", required: true, description: "Transaction location" },
                merchant_type: {
                    type: "string",
                    required: true,
                    description: "Type of merchant",
                    enum: ["Grocery", "Electronics", "Gas", "Restaurant", "Online"],
                },
            },
            output: {
                type: "string",
                description: "Fraud detection result",
                classes: ["Fraud", "Legitimate"],
            },
            metadata: {
                model_type: "classification",
                version: "2.5.0",
                created_by: "Security Team",
                description: "Batch fraud detection system",
            },
        },
    },
]

export const mockPredictions: Prediction[] = [
    // Signature 1-1 Predictions
    {
        id: "pred-1-1-1",
        signatureId: "sig-1-1",
        timestamp: "2024-01-20T10:30:00Z",
        inputs: { age: 45, tenure: 24, monthly_charges: 79.85, total_charges: 1889.5 },
        output: "Churn",
        confidence: 0.73,
        status: "correct",
        executionTime: 0.002,
    },
    {
        id: "pred-1-1-2",
        signatureId: "sig-1-1",
        timestamp: "2024-01-20T10:25:00Z",
        inputs: { age: 32, tenure: 12, monthly_charges: 65.2, total_charges: 782.4 },
        output: "No Churn",
        confidence: 0.89,
        status: "incorrect",
        actualValue: "Churn",
        executionTime: 0.001,
    },
    {
        id: "pred-1-1-3",
        signatureId: "sig-1-1",
        timestamp: "2024-01-20T10:20:00Z",
        inputs: { age: 28, tenure: 36, monthly_charges: 45.3, total_charges: 1630.8 },
        output: "No Churn",
        confidence: 0.92,
        status: "pending",
        executionTime: 0.002,
    },
    // Signature 1-2 Predictions
    {
        id: "pred-1-2-1",
        signatureId: "sig-1-2",
        timestamp: "2024-01-18T14:15:00Z",
        inputs: { age: 55, tenure: 6, monthly_charges: 95.4 },
        output: "Churn",
        confidence: 0.85,
        status: "correct",
        executionTime: 0.001,
    },
    {
        id: "pred-1-2-2",
        signatureId: "sig-1-2",
        timestamp: "2024-01-18T14:10:00Z",
        inputs: { age: 41, tenure: 18, monthly_charges: 72.1 },
        output: "No Churn",
        confidence: 0.78,
        status: "pending",
        executionTime: 0.002,
    },
    {
        id: "pred-1-2-3",
        signatureId: "sig-1-2",
        timestamp: "2024-01-18T14:05:00Z",
        inputs: { age: 29, tenure: 48, monthly_charges: 55.8 },
        output: "No Churn",
        confidence: 0.91,
        status: "correct",
        executionTime: 0.001,
    },
    // Signature 2-1 Predictions
    {
        id: "pred-2-1-1",
        signatureId: "sig-2-1",
        timestamp: "2024-01-20T11:00:00Z",
        inputs: { historical_sales: 125000, seasonality: 0.8, marketing_spend: 15000 },
        output: 142500,
        confidence: 0.84,
        status: "correct",
        executionTime: 0.003,
    },
    {
        id: "pred-2-1-2",
        signatureId: "sig-2-1",
        timestamp: "2024-01-20T10:55:00Z",
        inputs: { historical_sales: 98000, seasonality: 0.6, marketing_spend: 12000 },
        output: 108500,
        confidence: 0.79,
        status: "pending",
        executionTime: 0.002,
    },
    {
        id: "pred-2-1-3",
        signatureId: "sig-2-1",
        timestamp: "2024-01-20T10:50:00Z",
        inputs: { historical_sales: 156000, seasonality: 1.2, marketing_spend: 18000 },
        output: 187200,
        confidence: 0.88,
        status: "incorrect",
        actualValue: 195000,
        executionTime: 0.003,
    },
    // Signature 2-2 Predictions
    {
        id: "pred-2-2-1",
        signatureId: "sig-2-2",
        timestamp: "2024-01-19T16:30:00Z",
        inputs: { historical_sales: 125000, seasonality: 0.8, marketing_spend: 15000, competitor_data: 0.3 },
        output: 148750,
        confidence: 0.91,
        status: "correct",
        executionTime: 0.004,
    },
    {
        id: "pred-2-2-2",
        signatureId: "sig-2-2",
        timestamp: "2024-01-19T16:25:00Z",
        inputs: { historical_sales: 98000, seasonality: 0.6, marketing_spend: 12000, competitor_data: 0.4 },
        output: 112800,
        confidence: 0.86,
        status: "pending",
        executionTime: 0.003,
    },
    {
        id: "pred-2-2-3",
        signatureId: "sig-2-2",
        timestamp: "2024-01-19T16:20:00Z",
        inputs: { historical_sales: 156000, seasonality: 1.2, marketing_spend: 18000, competitor_data: 0.25 },
        output: 194400,
        confidence: 0.93,
        status: "correct",
        executionTime: 0.004,
    },
    // Signature 3-1 Predictions
    {
        id: "pred-3-1-1",
        signatureId: "sig-3-1",
        timestamp: "2024-01-20T11:30:00Z",
        inputs: { transaction_amount: 2500, location: "New York", time: "14:30", merchant_type: "Electronics" },
        output: "Fraud",
        confidence: 0.96,
        status: "correct",
        executionTime: 0.001,
    },
    {
        id: "pred-3-1-2",
        signatureId: "sig-3-1",
        timestamp: "2024-01-20T11:25:00Z",
        inputs: { transaction_amount: 45.99, location: "Chicago", time: "09:15", merchant_type: "Grocery" },
        output: "Legitimate",
        confidence: 0.98,
        status: "correct",
        executionTime: 0.001,
    },
    {
        id: "pred-3-1-3",
        signatureId: "sig-3-1",
        timestamp: "2024-01-20T11:20:00Z",
        inputs: { transaction_amount: 1200, location: "Miami", time: "23:45", merchant_type: "Gas" },
        output: "Fraud",
        confidence: 0.87,
        status: "incorrect",
        actualValue: "Legitimate",
        executionTime: 0.001,
    },
    // Signature 3-2 Predictions
    {
        id: "pred-3-2-1",
        signatureId: "sig-3-2",
        timestamp: "2024-01-18T09:00:00Z",
        inputs: { transaction_amount: 3500, location: "Los Angeles", merchant_type: "Electronics" },
        output: "Fraud",
        confidence: 0.94,
        status: "correct",
        executionTime: 0.002,
    },
    {
        id: "pred-3-2-2",
        signatureId: "sig-3-2",
        timestamp: "2024-01-18T08:55:00Z",
        inputs: { transaction_amount: 67.5, location: "Seattle", merchant_type: "Restaurant" },
        output: "Legitimate",
        confidence: 0.89,
        status: "pending",
        executionTime: 0.001,
    },
    {
        id: "pred-3-2-3",
        signatureId: "sig-3-2",
        timestamp: "2024-01-18T08:50:00Z",
        inputs: { transaction_amount: 890, location: "Boston", merchant_type: "Online" },
        output: "Legitimate",
        confidence: 0.76,
        status: "incorrect",
        actualValue: "Fraud",
        executionTime: 0.002,
    },
]
