/*
SPDX-License-Identifier: MIT
Copyright (c) 2025 Pablo Ulloa Santin
*/

export interface BulkPredictionRecord {
	name: string;
	inputs: Record<string, unknown>;
}

export interface SkippedRecord {
	line: number;
	name?: string;
	reason: string;
}

export interface ParseBulkPredictionResult {
	records: BulkPredictionRecord[];
	skipped: SkippedRecord[];
}

export type TabularPredictionRow = {
	line: number;
	values: unknown[];
};

type SignatureField = {
	name: string;
	kind: string;
	required: boolean;
};

const TEXT_KINDS = new Set(["text", "long-text", "date", "category", "mapped-category", "single-choice"]);

const isRecord = (value: unknown): value is Record<string, unknown> =>
	typeof value === "object" && value !== null && !Array.isArray(value);

const getString = (value: unknown): string | null =>
	typeof value === "string" && value.trim() ? value.trim() : null;

const getCellText = (value: unknown): string => {
	if (value instanceof Date) return value.toISOString().slice(0, 10);
	return value === null || value === undefined ? "" : String(value);
};

const getFieldName = (field: Record<string, unknown>): string | null => {
	if (isRecord(field.ui)) {
		const backendKey = getString(field.ui.backendKey);
		if (backendKey) return backendKey;
	}
	return getString(field.label) ?? getString(field.id);
};

const getSignatureFields = (signatureSchema: unknown): SignatureField[] => {
	if (!isRecord(signatureSchema) || !Array.isArray(signatureSchema.fields)) return [];
	return signatureSchema.fields.flatMap((field) => {
		if (!isRecord(field)) return [];
		const name = getFieldName(field);
		const kind = getString(field.kind);
		return name && kind ? [{ name, kind, required: field.required === true }] : [];
	});
};

const parseBoolean = (value: string): boolean | null => {
	switch (value.trim().toLowerCase()) {
		case "true":
		case "1":
		case "yes":
		case "si":
			return true;
		case "false":
		case "0":
		case "no":
			return false;
		default:
			return null;
	}
};

const coerceValue = (raw: unknown, field: SignatureField): { value?: unknown; error?: string } => {
	const text = getCellText(raw).trim();
	if (!text) {
		return field.required ? { error: `Missing required value for "${field.name}"` } : { value: undefined };
	}
	if (field.kind === "number" || field.kind === "rating") {
		const parsed = typeof raw === "number" ? raw : Number(text);
		return Number.isFinite(parsed) ? { value: parsed } : { error: `"${field.name}" must be a finite number` };
	}
	if (field.kind === "boolean") {
		if (typeof raw === "boolean") return { value: raw };
		const parsed = parseBoolean(text);
		return parsed === null ? { error: `"${field.name}" must be a boolean` } : { value: parsed };
	}
	if (field.kind === "multi-choice") {
		return { value: text.split(";").flatMap((item) => {
			const trimmed = item.trim();
			return trimmed ? [trimmed] : [];
		}) };
	}
	if (field.kind === "series") {
		try {
			const parsed: unknown = typeof raw === "string" ? JSON.parse(text) : raw;
			return Array.isArray(parsed) ? { value: parsed } : { error: `"${field.name}" must be a JSON array` };
		} catch {
			return { error: `"${field.name}" must be a JSON array` };
		}
	}
	if (TEXT_KINDS.has(field.kind)) return { value: text };
	if (text.startsWith("{") || text.startsWith("[")) {
		try {
			return { value: JSON.parse(text) as unknown };
		} catch {
			return { error: `"${field.name}" contains invalid JSON` };
		}
	}
	return { value: text };
};

const autogeneratedName = (base: number, index: number): string => `bulk-upload-${base + index + 1}`;

export function parseTabularPredictionRecords(
	rows: TabularPredictionRow[],
	signatureSchema: unknown,
	maxRecords = 10000,
	autoNameBase?: number,
): ParseBulkPredictionResult {
	if (rows.length === 0) return { records: [], skipped: [{ line: 1, reason: "File is empty" }] };

	const [headerRow, ...dataRows] = rows;
	const headers = headerRow.values.map((value) => getCellText(value).trim());
	const fields = getSignatureFields(signatureSchema);
	const fieldMap = new Map(fields.map((field) => [field.name, field]));
	const skipped: SkippedRecord[] = [];
	const hasNameHeader = headers[0] === "name";

	if (new Set(headers).size !== headers.length) {
		return { records: [], skipped: [{ line: headerRow.line, reason: "Headers must be unique" }] };
	}

	const inputHeaders = hasNameHeader ? headers.slice(1) : headers;
	if (!hasNameHeader && autoNameBase === undefined) {
		return {
			records: [],
			skipped: [{ line: headerRow.line, reason: 'Missing "name" column requires prediction id base' }],
		};
	}
	const missing = fields.reduce<string[]>((items, field) => {
		if (!inputHeaders.includes(field.name)) items.push(field.name);
		return items;
	}, []);
	const extra = inputHeaders.filter((header) => !fieldMap.has(header));
	if (missing.length > 0 || extra.length > 0) {
		return {
			records: [],
			skipped: [
				...(missing.length > 0 ? [{ line: headerRow.line, reason: `Missing input columns: ${missing.join(", ")}` }] : []),
				...(extra.length > 0 ? [{ line: headerRow.line, reason: `Unknown input columns: ${extra.join(", ")}` }] : []),
			],
		};
	}
	if (dataRows.length > maxRecords) {
		return { records: [], skipped: [{ line: 0, reason: `File exceeds maximum of ${maxRecords} records (found ${dataRows.length})` }] };
	}

	const records: BulkPredictionRecord[] = [];
	for (let rowIndex = 0; rowIndex < dataRows.length; rowIndex++) {
		const row = dataRows[rowIndex];
		const name = hasNameHeader ? getCellText(row.values[0]).trim() : autogeneratedName(autoNameBase ?? 0, rowIndex);
		if (!name) {
			skipped.push({ line: row.line, reason: 'Missing or empty "name" field' });
			continue;
		}

		const inputs: Record<string, unknown> = {};
		let rowError: string | null = null;
		for (let index = 0; index < inputHeaders.length; index++) {
			const field = fieldMap.get(inputHeaders[index]);
			if (!field) continue;
			const result = coerceValue(row.values[index + (hasNameHeader ? 1 : 0)], field);
			if (result.error) {
				rowError = result.error;
				break;
			}
			inputs[field.name] = result.value;
		}
		if (rowError) skipped.push({ line: row.line, name, reason: rowError });
		else records.push({ name, inputs });
	}
	return { records, skipped };
}
