#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10
COMPOSE=(docker compose --env-file "$ENV_FILE" -f docker-compose.prod.yml)
umask 077
restore_state=
cleanup_restore() {
  [[ -n "$restore_state" && -f "$restore_state" ]] || return 0
  ./scripts/smoke-restored-release.sh stop "$restore_state" "$ENV_FILE" "$RELEASE_COMPOSE" || true
  ./scripts/verify-production-backup.sh --destroy "$restore_state" || true
}
trap cleanup_restore EXIT INT TERM

banner "MLSuite production cutover"

stage "Preflight"
[[ -f "$ENV_FILE" ]] || { warn "$ENV_FILE does not exist; copy .env.example and fill it first"; exit 1; }
for command in docker curl find sha256sum sort; do command -v "$command" >/dev/null || { warn "missing command: $command"; exit 1; }; done
for key in DB_ADMIN_USER DB_ADMIN_PASS DB_LEGACY_OWNER DB_LEGACY_PASS DB_USER DB_PASS DB_MIGRATION_USER DB_MIGRATION_PASS STORAGE_ACCESS_KEY STORAGE_SECRET_KEY; do
  [[ -n "$(_existing "$key" || true)" ]] || { warn "$key must be set in $ENV_FILE"; exit 1; }
done
for key in PITR_PROVIDER PITR_OFFSITE_TARGET PITR_LAST_RESTORE_UTC RECOVERY_RPO_MINUTES RECOVERY_RTO_MINUTES; do
  [[ -n "$(_existing "$key" || true)" ]] || { warn "$key must be set in $ENV_FILE"; exit 1; }
done
[[ "$(_existing MODEL_MUTATIONS_REQUIRE_VERSION)" == true ]] || { warn "Production requires MODEL_MUTATIONS_REQUIRE_VERSION=true"; exit 1; }
[[ "$(_existing RECOVERY_RPO_MINUTES)" =~ ^[0-9]+$ && "$(_existing RECOVERY_RTO_MINUTES)" =~ ^[0-9]+$ ]] || { warn "RPO/RTO must be integer minutes"; exit 1; }
[[ "$(_existing PITR_LAST_RESTORE_UTC)" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$ ]] || { warn "PITR_LAST_RESTORE_UTC must use UTC ISO-8601"; exit 1; }
step "PITR provider: $(_existing PITR_PROVIDER); off-site target: $(_existing PITR_OFFSITE_TARGET); last restore: $(_existing PITR_LAST_RESTORE_UTC)."
confirm "Is WAL archiving healthy and is the recorded restore drill inside the declared RPO/RTO policy?" || exit 1
"${COMPOSE[@]}" config --quiet
say "Compose configuration is valid. This wizard never performs an automatic destructive restore."

stage "Immutable release"
ask API_VERSION "API image tag (must be an immutable build-* tag):"
[[ "$API_VERSION" == build-* ]] || { warn "API_VERSION must use an immutable build-* release"; exit 1; }
write_env API_VERSION "$API_VERSION"
ask RELEASE_COMPOSE "Digest-pinned Compose override inside this repository:"
[[ "$RELEASE_COMPOSE" != /* && "$RELEASE_COMPOSE" != *..* && -f "$RELEASE_COMPOSE" ]] || { warn "Release override must be an existing path inside this repository"; exit 1; }
write_env RELEASE_COMPOSE "$RELEASE_COMPOSE"
COMPOSE+=(-f "$RELEASE_COMPOSE")
"${COMPOSE[@]}" config --quiet
step "Verify the release checksums and digest-pinned override using docs/RELEASES.md."
confirm "Have image signatures/checksums and all CI required checks been verified?" || exit 1

stage "Write freeze"
warn "Pause traffic before the final backups; the API will remain offline through canary validation."
confirm "Are new uploads, edits, predictions, feedback and administrative writes stopped?" || exit 1
"${COMPOSE[@]}" stop frontend spring-app
say "Frontend and API are stopped so PostgreSQL and MinIO are captured at one write-consistent point."

stage "PostgreSQL backup"
backup_dir="backups/production-$(date -u +%Y%m%dT%H%M%SZ)"
mkdir -p "$backup_dir"
"${COMPOSE[@]}" up -d postgres minio
db_user=$(_existing DB_ADMIN_USER); legacy_user=$(_existing DB_LEGACY_OWNER); db_name=$(_existing DB_PROD)
if ! "${COMPOSE[@]}" exec -T postgres pg_dump -U "$db_user" -d "$db_name" -Fc > "$backup_dir/postgres.dump"; then
  "${COMPOSE[@]}" exec -T postgres pg_dump -U "$legacy_user" -d "$db_name" -Fc > "$backup_dir/postgres.dump"
fi
sha256sum "$backup_dir/postgres.dump" > "$backup_dir/postgres.dump.sha256"
say "Created $backup_dir/postgres.dump. Keep WAL/PITR coverage from before the freeze."

stage "Artifact backup"
project=$(_existing COMPOSE_PROJECT_NAME || true); project=${project:-mlsuite}
storage_bucket=$(_existing STORAGE_BUCKET)
[[ "$storage_bucket" =~ ^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$ ]] || { warn "STORAGE_BUCKET is not a valid S3 bucket name"; exit 1; }
minio_volume="${project}_minio_data"
docker volume inspect "$minio_volume" >/dev/null
"${COMPOSE[@]}" stop minio
MSYS_NO_PATHCONV=1 docker run --rm -v "$minio_volume:/data:ro" postgres:17.11-alpine3.24 \
  tar -C /data -czf - . > "$backup_dir/minio-data.tar.gz"
printf '%s\n' "$storage_bucket" > "$backup_dir/storage.bucket"
(cd "$backup_dir" && sha256sum postgres.dump minio-data.tar.gz storage.bucket > backup.manifest)
"${COMPOSE[@]}" up -d minio minio-init
say "Copy $backup_dir to an encrypted target in a separate failure domain before continuing."
confirm "Is the encrypted database and artifact backup now stored outside this host?" || exit 1

stage "Restore rehearsal"
baseline_flag=
say "Existing pre-Flyway databases may be baselined only after comparing them with V1__baseline.sql."
confirm "Is this a verified pre-Flyway schema that exactly matches V1 and requires the one-time baseline?" && baseline_flag=--baseline
./scripts/verify-production-backup.sh "$backup_dir" --keep
restore_state="$PWD/$backup_dir/restore.env"
./scripts/smoke-restored-release.sh start "$restore_state" "$ENV_FILE" "$RELEASE_COMPOSE" "$baseline_flag"
restore_smoke_port=$(_existing RESTORE_SMOKE_PORT || true); restore_smoke_port=${restore_smoke_port:-18080}
step "Against http://127.0.0.1:${restore_smoke_port}, exercise login, model download, prediction, review and export."
confirm "Did every restored-release smoke test pass?" || exit 1
cleanup_restore
restore_state=

stage "Database migration"
if [[ "$baseline_flag" == --baseline ]]; then
  "${COMPOSE[@]}" run --rm -e FLYWAY_BASELINE_ON_MIGRATE=true -e FLYWAY_BASELINE_VERSION=1 db-migrate
else
  "${COMPOSE[@]}" run --rm db-migrate
fi

stage "Artifact migration"
"${COMPOSE[@]}" --profile operations run --rm -e ARTIFACT_MIGRATION_COMMAND=status artifact-migrate
"${COMPOSE[@]}" --profile operations run --rm -e ARTIFACT_MIGRATION_COMMAND=migrate artifact-migrate
"${COMPOSE[@]}" --profile operations run --rm -e ARTIFACT_MIGRATION_COMMAND=verify artifact-migrate
confirm "Does final status contain no FAILED, RUNNING, INLINE_ONLY or UNVERIFIED rows?" || exit 1

stage "Canary and readiness"
"${COMPOSE[@]}" up -d ops-agent py-analyzer
"${COMPOSE[@]}" up -d --no-deps spring-app
ask READINESS_URL "Externally reachable API base URL (for example https://api.example.com):"
curl --fail --show-error --silent "$READINESS_URL/actuator/health/readiness"
step "Run authenticated smoke tests for upload, prediction, review and export against the canary."
confirm "Did readiness and all smoke tests pass?" || exit 1

stage "Promotion and rollback record"
say "Promote traffic gradually, then start frontend with: docker compose ... up -d frontend"
say "Application rollback: restore the previous immutable image while inline model_file copies remain."
say "State rollback: stop writes and restore PostgreSQL plus MinIO from the same backup point together."
confirm "Is the previous image digest, backup path and rollback owner recorded in the release ticket?" || exit 1
"${COMPOSE[@]}" up -d frontend

trap - EXIT INT TERM
finish
